# Generated by Django 5.0.4 on 2024-05-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookno', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('mobile', models.CharField(blank=True, max_length=256, null=True)),
                ('product_no', models.CharField(max_length=256)),
                ('product_name', models.CharField(max_length=256)),
                ('product_price', models.FloatField()),
                ('advance_paid', models.FloatField()),
                ('advance_paid_date', models.DateTimeField()),
                ('gurdian', models.CharField(max_length=256)),
                ('total_emi_no', models.IntegerField()),
                ('emi_amount', models.FloatField()),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('due_dt', models.DateField(verbose_name='Date')),
            ],
            options={
                'db_table': 'emis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('leader_name', models.CharField(max_length=256)),
                ('mobile', models.CharField(blank=True, max_length=256, null=True)),
                ('day', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'groups',
                'managed': False,
            },
        ),
    ]
